import type { City, ItineraryItem } from '../types/travel';

export const POPULAR_DESTINATIONS: City[] = [
  {
    id: 'tokyo-jp',
    name: 'Tokyo',
    country: 'Japan',
    countryCode: 'JP',
    latitude: 35.6762,
    longitude: 139.6503,
    timezone: 'Asia/Tokyo',
    population: 13960000,
    currency: 'JPY (¥)',
    language: 'Japanese',
    image: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1600&q=80',
    description: 'A vibrant metropolis where ultra-modern skyscrapers stand alongside centuries-old historic shrines and world-renowned gastronomy.',
  },
  {
    id: 'paris-fr',
    name: 'Paris',
    country: 'France',
    countryCode: 'FR',
    latitude: 48.8566,
    longitude: 2.3522,
    timezone: 'Europe/Paris',
    population: 2161000,
    currency: 'EUR (€)',
    language: 'French',
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1600&q=80',
    description: 'The City of Light captivates travelers with its timeless art museums, Haussmannian boulevards, and world-class culinary charm.',
  },
  {
    id: 'rome-it',
    name: 'Rome',
    country: 'Italy',
    countryCode: 'IT',
    latitude: 41.9028,
    longitude: 12.4964,
    timezone: 'Europe/Rome',
    population: 2873000,
    currency: 'EUR (€)',
    language: 'Italian',
    image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=1600&q=80',
    description: 'An open-air museum filled with ancient Roman ruins, Baroque fountains, sunlit piazzas, and authentic trattorias.',
  },
  {
    id: 'bali-id',
    name: 'Bali',
    country: 'Indonesia',
    countryCode: 'ID',
    latitude: -8.4095,
    longitude: 115.1889,
    timezone: 'Asia/Makassar',
    population: 4362000,
    currency: 'IDR (Rp)',
    language: 'Indonesian / Balinese',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1600&q=80',
    description: 'The Island of the Gods offers lush emerald rice terraces, cliffside ocean temples, vibrant surf breaks, and spiritual serenity.',
  },
  {
    id: 'nyc-us',
    name: 'New York',
    country: 'United States',
    countryCode: 'US',
    latitude: 40.7128,
    longitude: -74.0060,
    timezone: 'America/New_York',
    population: 8336000,
    currency: 'USD ($)',
    language: 'English',
    image: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&w=1600&q=80',
    description: 'The iconic cultural and financial capital known for Broadway theaters, Central Park strolls, and an unmatched skyline.',
  },
  {
    id: 'barcelona-es',
    name: 'Barcelona',
    country: 'Spain',
    countryCode: 'ES',
    latitude: 41.3851,
    longitude: 2.1734,
    timezone: 'Europe/Madrid',
    population: 1620000,
    currency: 'EUR (€)',
    language: 'Spanish / Catalan',
    image: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?auto=format&fit=crop&w=1600&q=80',
    description: 'A Mediterranean jewel blending Gaudí whimsical architecture, sun-soaked beaches, tapas bars, and lively Gothic Quarter alleys.',
  },
  {
    id: 'london-gb',
    name: 'London',
    country: 'United Kingdom',
    countryCode: 'GB',
    latitude: 51.5074,
    longitude: -0.1278,
    timezone: 'Europe/London',
    population: 8982000,
    currency: 'GBP (£)',
    language: 'English',
    image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1600&q=80',
    description: 'A global crossroads where royal palaces meet cutting-edge art galleries, iconic red double-deckers, and cozy historic pubs.',
  },
  {
    id: 'dubai-ae',
    name: 'Dubai',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    latitude: 25.2048,
    longitude: 55.2708,
    timezone: 'Asia/Dubai',
    population: 3331000,
    currency: 'AED (د.إ)',
    language: 'Arabic / English',
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1600&q=80',
    description: 'A futuristic oasis of architectural marvels, luxury shopping, desert dunes, and golden coastline experiences.',
  }
];

export const DEFAULT_INITIAL_ACTIVITIES: Record<string, ItineraryItem[]> = {
  'tokyo-jp': [
    {
      id: 'act-1',
      dayIndex: 1,
      time: '09:00',
      title: 'Meiji Jingu Shrine Stroll',
      location: 'Shibuya, Tokyo',
      category: 'sightseeing',
      cost: 0,
      notes: 'Peaceful morning walk through the cedar forest before crowds arrive.',
      completed: true,
    },
    {
      id: 'act-2',
      dayIndex: 1,
      time: '12:30',
      title: 'Harajuku Ramen & Street Treats',
      location: 'Takeshita Street, Harajuku',
      category: 'food',
      cost: 25,
      notes: 'Try the famous matcha soft serve and tonkotsu broth.',
      completed: false,
    },
    {
      id: 'act-3',
      dayIndex: 1,
      time: '15:30',
      title: 'Shibuya Sky Observatory',
      location: 'Shibuya Scramble Square',
      category: 'sightseeing',
      cost: 22,
      notes: 'Spectacular 360-degree sunset view over Shibuya crossing.',
      completed: false,
    },
    {
      id: 'act-4',
      dayIndex: 1,
      time: '19:00',
      title: 'Izakaya Dinner in Omoide Yokocho',
      location: 'Shinjuku, Tokyo',
      category: 'food',
      cost: 45,
      notes: 'Grilled yakitori skewers and draft beer in vintage alleyway stalls.',
      completed: false,
    },
    {
      id: 'act-5',
      dayIndex: 2,
      time: '08:30',
      title: 'Senso-ji Temple & Nakamise Dori',
      location: 'Asakusa, Tokyo',
      category: 'sightseeing',
      cost: 0,
      notes: 'Ancient Buddhist temple with traditional snack vendors.',
      completed: false,
    },
    {
      id: 'act-6',
      dayIndex: 2,
      time: '13:00',
      title: 'teamLab Planets Digital Art Immersion',
      location: 'Toyosu, Tokyo',
      category: 'activity',
      cost: 38,
      notes: 'Sensory water and light exhibits - bring shorts or rolled trousers!',
      completed: false,
    },
    {
      id: 'act-7',
      dayIndex: 2,
      time: '18:00',
      title: 'Ginza Shopping & Sushi Counter',
      location: 'Ginza District',
      category: 'shopping',
      cost: 95,
      notes: 'High-end department stores followed by omakase dinner.',
      completed: false,
    },
    {
      id: 'act-8',
      dayIndex: 3,
      time: '10:00',
      title: 'Akihabara Tech & Anime Exploration',
      location: 'Akihabara Electric Town',
      category: 'activity',
      cost: 30,
      notes: 'Explore multi-story retro game shops and manga cafes.',
      completed: false,
    },
    {
      id: 'act-9',
      dayIndex: 3,
      time: '16:00',
      title: 'Shinjuku Gyoen National Garden',
      location: 'Shinjuku, Tokyo',
      category: 'relaxation',
      cost: 5,
      notes: 'Picnic and relaxing garden tea ceremony.',
      completed: false,
    }
  ]
};
