export interface Coordinates {
  latitude: number;
  longitude: number;
}

export interface City {
  id: number | string;
  name: string;
  country: string;
  countryCode: string;
  latitude: number;
  longitude: number;
  timezone?: string;
  population?: number;
  image?: string;
  description?: string;
  currency?: string;
  language?: string;
}

export interface DailyForecast {
  date: string;
  dayName: string;
  maxTemp: number;
  minTemp: number;
  weatherCode: number;
  weatherDescription: string;
  weatherIcon: string;
  precipitationProb: number;
}

export interface HourlyForecast {
  time: string;
  temp: number;
  weatherCode: number;
  precipitationProb: number;
}

export interface WeatherData {
  temperature: number;
  apparentTemperature: number;
  weatherCode: number;
  weatherDescription: string;
  weatherIcon: string;
  isDay: boolean;
  windSpeed: number;
  humidity: number;
  precipitation: number;
  uvIndex: number;
  daily: DailyForecast[];
  hourly: HourlyForecast[];
  lastUpdated: string;
}

export type ActivityCategory = 
  | 'sightseeing' 
  | 'food' 
  | 'transport' 
  | 'lodging' 
  | 'activity' 
  | 'relaxation' 
  | 'shopping';

export interface ItineraryItem {
  id: string;
  dayIndex: number;
  time: string;
  title: string;
  location: string;
  category: ActivityCategory;
  cost: number;
  notes?: string;
  completed: boolean;
  openingHours?: string;
  bestTimeToVisit?: string;
  transitInfo?: string;
  weatherNote?: string;
  accessibilityStatus?: 'open' | 'caution' | 'closed';
  accessibilityNote?: string;
  isMustVisit?: boolean;
}

export interface PackingItem {
  id: string;
  name: string;
  category: 'essentials' | 'clothing' | 'toiletries' | 'gadgets' | 'weather';
  packed: boolean;
  autoGenerated?: boolean;
}

export interface AttractionRecommendation {
  id: string;
  title: string;
  description: string;
  category: ActivityCategory;
  estimatedCost: number;
  currency: string;
  openingHours: string;
  bestTimeToVisit: string;
  accessibility: string;
  transitInfo?: string;
  isMustVisit: boolean;
  image?: string;
}

export interface GeminiSuggestion {
  id: string;
  title: string;
  reason: string;
  category: ActivityCategory;
  suggestedTime: string;
  estimatedCost: number;
  accessibility: string;
  openingHours: string;
  transitInfo?: string;
  bestTimeToVisit?: string;
  isMustVisit?: boolean;
}

export interface ReadyMadeTourPlan {
  id: string;
  name: string;
  theme: string;
  description: string;
  durationDays: number;
  estimatedTotalCost: number;
  highlights: string[];
  items: ItineraryItem[];
}

export type PlanningMode = 'manual' | 'ai';

export interface FamilyMember {
  id: string;
  type: 'adult' | 'child' | 'senior';
  age: number;
  label?: string;
}

export interface TravelerGroupProfile {
  numberOfHeads: number;
  ageGroup: string; // e.g. "Young Adults (18-35)", "Family with Kids", "Seniors (60+)", "Mixed Group"
  travelStyle: string; // e.g. "Relaxed Pace", "Cultural & Sightseeing", "Adventure & Nature", "Budget Friendly"
  members?: FamilyMember[];
}

export interface TripPlan {
  id: string;
  title: string;
  cityName: string;
  country: string;
  city: City;
  origin?: string; // Starting from where
  startDate: string;
  endDate: string;
  daysCount: number;
  budget: number;
  currency: string;
  planningMode?: PlanningMode;
  groupProfile?: TravelerGroupProfile;
  isConfirmed?: boolean;
  items: ItineraryItem[];
  packingList: PackingItem[];
  createdAt: string;
}

