import React, { useState } from 'react';
import { 
  CheckSquare, 
  Square, 
  Plus, 
  Trash2, 
  Sparkles, 
  Backpack, 
  CloudRain
} from 'lucide-react';
import { useTrip } from '../../context/TripContext';
import type { PackingItem } from '../../types/travel';

export const SmartPackingList: React.FC = () => {
  const { 
    activeTrip, 
    togglePackingItem, 
    addPackingItem, 
    deletePackingItem, 
    weather 
  } = useTrip();

  const [newItemName, setNewItemName] = useState('');
  const [selectedCategory, setSelectedCategory] = useState<PackingItem['category']>('essentials');

  const items = activeTrip.packingList || [];
  const packedCount = items.filter(i => i.packed).length;
  const progressPercent = items.length > 0 ? Math.round((packedCount / items.length) * 100) : 0;

  const handleAdd = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newItemName.trim()) return;
    addPackingItem(newItemName, selectedCategory);
    setNewItemName('');
  };

  return (
    <div className="glass-card rounded-2xl p-5 sm:p-6 border border-slate-800 shadow-glass">
      
      <div className="flex items-center justify-between pb-4 border-b border-slate-800">
        <div className="flex items-center gap-2.5">
          <span className="p-1.5 rounded-xl bg-teal-500/10 text-teal-400">
            <Backpack className="w-4 h-4" />
          </span>
          <div>
            <h3 className="text-sm font-bold text-white tracking-wide uppercase">
              Smart Packing Assistant
            </h3>
            <p className="text-xs text-slate-400">
              {packedCount} of {items.length} items packed ({progressPercent}%)
            </p>
          </div>
        </div>

        {weather && (weather.precipitation > 0 || (weather.daily[0]?.precipitationProb ?? 0) > 40) && (
          <span className="hidden sm:inline-flex items-center gap-1 text-[11px] px-2.5 py-1 rounded-full bg-sky-500/15 border border-sky-500/30 text-sky-300">
            <CloudRain className="w-3.5 h-3.5" /> Rain gear recommended
          </span>
        )}
      </div>

      <div className="w-full bg-slate-800/80 rounded-full h-1.5 mt-4 overflow-hidden">
        <div 
          className="h-full bg-gradient-to-r from-teal-400 to-sky-500 transition-all duration-300 rounded-full"
          style={{ width: `${progressPercent}%` }}
        />
      </div>

      <form onSubmit={handleAdd} className="mt-4 flex gap-2">
        <input
          type="text"
          value={newItemName}
          onChange={(e) => setNewItemName(e.target.value)}
          placeholder="Add packing item (e.g. Travel adaptor)..."
          className="flex-1 px-3 py-1.5 rounded-xl text-xs bg-slate-900 border border-slate-700 text-white placeholder-slate-400 focus:outline-none focus:ring-1 focus:ring-sky-500"
        />
        <select
          value={selectedCategory}
          onChange={(e) => setSelectedCategory(e.target.value as PackingItem['category'])}
          className="px-2 py-1.5 rounded-xl text-xs bg-slate-900 border border-slate-700 text-slate-300 focus:outline-none focus:ring-1 focus:ring-sky-500 capitalize"
        >
          <option value="essentials">Essentials</option>
          <option value="clothing">Clothing</option>
          <option value="gadgets">Gadgets</option>
          <option value="toiletries">Toiletries</option>
          <option value="weather">Weather Gear</option>
        </select>
        <button
          type="submit"
          className="px-3 py-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-white text-xs font-semibold flex items-center gap-1 transition-colors shrink-0"
        >
          <Plus className="w-3.5 h-3.5" />
          <span>Add</span>
        </button>
      </form>

      <div className="mt-3.5 space-y-1.5 max-h-56 overflow-y-auto pr-1">
        {items.map((item) => (
          <div
            key={item.id}
            className={`p-2.5 rounded-xl border flex items-center justify-between transition-colors ${
              item.packed 
                ? 'bg-slate-900/40 border-slate-850 opacity-60' 
                : 'bg-slate-850/60 border-slate-800 hover:bg-slate-800/80'
            }`}
          >
            <button
              onClick={() => togglePackingItem(item.id)}
              className="flex items-center gap-2.5 text-left flex-1 min-w-0"
            >
              {item.packed ? (
                <CheckSquare className="w-4 h-4 text-emerald-400 shrink-0" />
              ) : (
                <Square className="w-4 h-4 text-slate-500 hover:text-sky-400 shrink-0" />
              )}
              <span className={`text-xs font-medium truncate ${item.packed ? 'line-through text-slate-400' : 'text-slate-200'}`}>
                {item.name}
              </span>
              {item.autoGenerated && (
                <span className="text-[10px] px-1.5 py-0.2 rounded bg-sky-500/10 text-sky-300 font-mono flex items-center gap-0.5">
                  <Sparkles className="w-2.5 h-2.5 text-amber-300" /> Weather tip
                </span>
              )}
            </button>

            <button
              onClick={() => deletePackingItem(item.id)}
              className="text-slate-600 hover:text-rose-400 p-1 rounded transition-colors"
              title="Remove item"
            >
              <Trash2 className="w-3 h-3" />
            </button>
          </div>
        ))}
      </div>

    </div>
  );
};
